// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQa8s5Mql5KMguX0KF1BLV6vVW-kgNGc',
    appId: '1:1086032535936:web:3d6639c22855ce577f2165',
    messagingSenderId: '1086032535936',
    projectId: 'takay-khuda-metai',
    authDomain: 'takay-khuda-metai.firebaseapp.com',
    databaseURL: 'https://takay-khuda-metai-default-rtdb.firebaseio.com',
    storageBucket: 'takay-khuda-metai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsHwat19TFlxElIJD18Yg46OvbKVUOwA',
    appId: '1:1086032535936:android:6370916774611d457f2165',
    messagingSenderId: '1086032535936',
    projectId: 'takay-khuda-metai',
    databaseURL: 'https://takay-khuda-metai-default-rtdb.firebaseio.com',
    storageBucket: 'takay-khuda-metai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTHV_e7XVpKbs9I9_Yqzw8K4KgxstSqBU',
    appId: '1:1086032535936:ios:24fee26bddd753887f2165',
    messagingSenderId: '1086032535936',
    projectId: 'takay-khuda-metai',
    databaseURL: 'https://takay-khuda-metai-default-rtdb.firebaseio.com',
    storageBucket: 'takay-khuda-metai.firebasestorage.app',
    iosBundleId: 'com.mrtechbd.mrexpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTHV_e7XVpKbs9I9_Yqzw8K4KgxstSqBU',
    appId: '1:1086032535936:ios:c9f1172865c723667f2165',
    messagingSenderId: '1086032535936',
    projectId: 'takay-khuda-metai',
    databaseURL: 'https://takay-khuda-metai-default-rtdb.firebaseio.com',
    storageBucket: 'takay-khuda-metai.firebasestorage.app',
    iosBundleId: 'com.example.mrExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQa8s5Mql5KMguX0KF1BLV6vVW-kgNGc',
    appId: '1:1086032535936:web:1c39b8a1cd24e8d07f2165',
    messagingSenderId: '1086032535936',
    projectId: 'takay-khuda-metai',
    authDomain: 'takay-khuda-metai.firebaseapp.com',
    databaseURL: 'https://takay-khuda-metai-default-rtdb.firebaseio.com',
    storageBucket: 'takay-khuda-metai.firebasestorage.app',
  );
}
